### ISSUE TITLE
CloudFront Distribution for Example Data S3 Bucket

### ISSUE THREAD

**Issue by ckunki** [exasol/ai-lab#301]
Adding an IBIS Notebook to the AI Lab requires additional resources on AWS as we expect the involved example data to be of significant volume. 

Additionally, the data should be retrievable in a non-supervised way, i.e. cannot be guarded by a captcha, as this is the case for the existing S3 bucket containing the AI-Lab VM images.

The current ticket therefore requests to enhance the AI-Lab by 
* CF Template for S3 Bucket with a Cloudfront distribution for Example Data
* CF Template for WAF without Captcha

AI-Lab should allow applying these templates independently of the existing templates for VM bucket and related WAF by offering separate commands or CLI options.

#### Tasks 
* [x] Refactor existing code and tests to allow creating an additional cloudformation stack for example data PR [#310](#310)
* [x] add test that template for vm bucket and its WAF is rendered identically to the old version.

Add support for the AI-Lab example data S3 bucket and WAF:
* [x] Duplicate and modify jinja templates [vm_bucket_cloudformation.jinja.yaml](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/templates/vm_bucket_cloudformation.jinja.yaml) and [waf_cloudformation.jinja.yaml](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/templates/waf_cloudformation.jinja.yaml)
* [x] Enhance ai-lab inject additional configuration parameters into jinja templates
* [x] Add CLI options 
* [x] Add CLI tests
* [x] Update Developer Guide
* [x] Do we need to update or enhance tests for actual buckets and waf?
* [x] Do we need to support `allowed_ip` for example data WAF (VM bucket WAF only uses this for its captcha)?

**Comment by ckunki** [comment]
[print_assets.py](https://github.com/exasol/ai-lab/blob/main/exasol/ds/sandbox/lib/asset_printing/print_assets.py) allows to print all assets of the AI-Lab. Should Example Data be printed, too?
